import { SERVICE_NAME } from "./paths.mjs";

const TUNNEL_ID_PATTERN = /^tunnel_[0-9a-f]{32}$/;

export function assertTunnelId(tunnelId) {
  if (!TUNNEL_ID_PATTERN.test(tunnelId ?? "")) {
    throw new Error("Tunnel IDs look like tunnel_ followed by 32 lowercase hex characters.");
  }
}

const yamlString = (value) => JSON.stringify(String(value));

/**
 * The tunnel-client profile. It holds no secrets: `file:` values are read by
 * tunnel-client at startup. The T3 bearer is injected on every request to the
 * local MCP origin, including the startup initialize probe and discovery.
 */
export function renderTunnelProfile({
  tunnelId,
  runtimeKeyFile,
  t3McpUrl,
  t3AuthorizationFile,
  healthAddr,
}) {
  assertTunnelId(tunnelId);
  const authorization = yamlString(`file:${t3AuthorizationFile}`);
  return `# Generated by \`t3mcp configure\`. Contains no secrets; file: values are
# read by tunnel-client at startup. Restart the service after changing them.
config_version: 1
control_plane:
  tunnel_id: ${tunnelId}
  api_key: ${yamlString(`file:${runtimeKeyFile}`)}
log:
  level: info
  format: struct-text
health:
  listen_addr: ${yamlString(healthAddr)}
mcp:
  server_urls:
    - channel: main
      url: ${yamlString(t3McpUrl)}
  extra_headers:
    Authorization: ${authorization}
  discovery_extra_headers:
    Authorization: ${authorization}
  # Wait for T3 Code to listen after a reboot before polling for work.
  startup_wait_timeout: 120s
`;
}

const quoteArg = (value) => (/^[\w@%+=:,./-]+$/.test(value) ? value : JSON.stringify(value));

export function renderTunnelService({ tunnelClientBin, profileFile }) {
  return `[Unit]
Description=T3mcp: OpenAI Secure MCP Tunnel client for T3 Code
Documentation=https://github.com/openai/tunnel-client
After=network-online.target t3code.service
Wants=network-online.target

[Service]
Type=simple
ExecStart=${quoteArg(tunnelClientBin)} run --profile-file ${quoteArg(profileFile)}
Restart=always
RestartSec=10
UMask=0077
NoNewPrivileges=yes
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=default.target
`;
}

export function renderExpiryCheck({ nodeBin, cliPath, warnDays }) {
  const service = `[Unit]
Description=T3mcp: warn before the T3 MCP credential expires
After=${SERVICE_NAME}

[Service]
Type=oneshot
ExecStart=${quoteArg(nodeBin)} ${quoteArg(cliPath)} expiry-check --warn-days ${warnDays}
`;
  const timer = `[Unit]
Description=T3mcp: daily T3 MCP credential expiry check

[Timer]
OnCalendar=daily
OnBootSec=5min
Persistent=true

[Install]
WantedBy=timers.target
`;
  return { service, timer };
}
